name: Zfoto
favicon: null
layout_spectrum: 0.24555
typography_spectrum: 0.0000975604634732008
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0
  lightness: 0.7132790354080498
  saturation: 0.49906014697626233
  rhythmicContrast: 0
purpose: []
