name: Zfoto
favicon: null
layout_spectrum: 0.37382
typography_spectrum: 0.0000975604634732008
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a1aab1'
    - '#687888'
    - '#d7d8da'
    - '#2d3035'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
